.\" SPDX-License-Identifier: MIT
.TH JITTERSAMPLES 1
.SH NAME
jittersamples \- decodes collected samples by jitterdebugger
.SH SYNOPSIS
.B jittersamples hist [OPTIONS]
.SH DESCRIPTION
.B jittersamples
prints all samples stored by jitterdebugger to standard output.

The input file is expected to be in raw format. The default output is
in CSV (Comma Separated Values) format.

The fields are:
.IP \[bu]
CPUID
.IP \[bu]
Timestamp in seconds
.IP \[bu]
Wake up latency in micro seconds
.SH OPTIONS
.TP
.BI "-h, --help"
Show help text and exit.
.TP
.BI "-f, --format" FMT
Set output format. Supported formats are CSV and HDF5. For HDF5 an
output file has to be provided via --output command line.
.TP
.BI "-o, --output" FILE
Write data to FILE instead to STDOUT.
.SH EXAMPLES
.EX
  # jitterdebugger -o samples.raw
  ^C
  # jittersamples samples.raw | head
  0;1114.936950838;9
  0;1114.937204763;3
  0;1114.937458457;3
  0;1114.937711970;3
  0;1114.937965595;3
  0;1114.938218986;3
  0;1114.938472416;3
  0;1114.938725788;3
  0;1114.938979191;3
  0;1114.939232594;3
.EE
.SH SEE ALSO
.ad l
.nh
.BR jitterdebugger (1)
.BR jitterplot (1)
