#!/usr/bin/env python3
# SPDX-License-Identifier: MIT

import sys
import json
import argparse
import matplotlib.pyplot as plt
import pandas as pd

__version__ = '0.3'

def plot_histogram(filename):
    with open(filename) as file:
        rawdata = json.load(file)

    cpu_id = 0
    fig, ax = plt.subplots()
    while True:
        if str(cpu_id) not in rawdata['cpu']:
            break

        cid = str(cpu_id)
        data = rawdata['cpu'][cid]
        d = {int(k): int(v) for k, v in data['histogram'].items()}
        l = 'cpu{} max{:>3} avg{:>5} min{:>3}'.format(
            cid,
            rawdata['cpu'][cid]['max'],
            rawdata['cpu'][cid]['avg'],
            rawdata['cpu'][cid]['min'])
        ax.bar(list(d.keys()), list(d.values()), log=True, alpha=0.5, label=l)

        cpu_id = cpu_id + 1

    L = ax.legend()
    plt.setp(L.texts, family='monospace')
    plt.show()

def load_hdf(filename):
    df = pd.read_hdf(filename)
    return df

def plot_all_cpus(df):
    ids = df["CPUID"].unique()
    max_jitter = max(df["Value"])

    fig = plt.figure()
    axes = fig.subplots(len(ids))
    for ax, data in zip(
        iter(axes),
        (df[df["CPUID"] == id] for id in ids),
    ):
        data["Time"] = data["Seconds"] + data["Nanoseconds"] * 10**-9
        ax.plot("Time", "Value", data=data)
        ax.set_xlabel("Time [s]")
        ax.set_ylabel("Latency [us]")
        ax.set_ylim(ymin=0, ymax=max_jitter)
    plt.show()


def main():
    ap = argparse.ArgumentParser(description='Plot statistics collected with jitterdebugger')
    ap.add_argument('--version', action='version',
                    version='%(prog)s ' + __version__)
    sap = ap.add_subparsers(dest='cmd')

    hrs = sap.add_parser('hist', help='Print historgram')
    hrs.add_argument('HIST_FILE')

    srs = sap.add_parser('samples', help='Plot samples graph')
    srs.add_argument('SAMPLE_FILE')

    args = ap.parse_args(sys.argv[1:])
    if args.cmd == 'hist':
        plot_histogram(args.HIST_FILE)
    elif args.cmd == 'samples':
        df = load_hdf(args.SAMPLE_FILE)
        plot_all_cpus(df)

if __name__ == '__main__':
    main()
